### ISSUE TITLE
documentation of natural deduction calculus

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#626]
The natural deduction calculus should be documented in the user manual by:

1. latexing the rules for reference purposes in Appendix B and
2. extending Section 3.3. by a small example that demonstrates the constructors of the natural deduction rules.

**Comment by gebner** [comment]
@mschlaipfer @MarielleLouise Can either one of you please take care of the documentation?

**Comment by mschlaipfer** [comment]
I will take care of it.

**Comment by gebner** [comment]
Fixed by @mschlaipfer in aa9f286326893449110688204e38b8c8dc44923e.

**Comment by gebner** [comment]
Ok, there's still something missing.  We should still extend Section 3.3.

**Comment by mschlaipfer** [comment]
Fixed in https://github.com/gapt/gapt/commit/33e5e86f34b8eaa966a6974b1a9a6e5c37c76b80

**Comment by mschlaipfer** [comment]
The `\newpage` is still in my branch, though.

**Comment by shetzl** [comment]
Thanks for doing this so quickly! But I think that the appendix is still missing BottomElimRule.

**Comment by mschlaipfer** [comment]
Sorry, good catch! Added in https://github.com/gapt/gapt/commit/5dfe79e26badbf617f80bf22b14596477f5545ce. It is currently right after the page break. Not sure if we want to pay attention to keeping similar rules on the same page.

**Comment by gebner** [comment]
Aren't we missing a top-introduction rule as well?

**Comment by MarielleLouise** [comment]
Thanks for taking care of the documentation Matthias! 

There is no top-introduction rule in the natural deduction now, should we add it? I am not familiar with such a rule but I guess its just to have top as an axiom is that right?

**Comment by gebner** [comment]
@MarielleLouise Yes, the rule is just `⊢ ⊤`, and we need to have it.  Otherwise the ND calculus is incomplete for propositional logic, let alone first-order.

**Comment by MarielleLouise** [comment]
Ok, I will add it.

**Comment by gebner** [comment]
@MarielleLouise Thanks!
